// --------------------
// OEFLAGS/OEPREFS
// --------------------
// See the documentation for more information about these

#define M_OEFLAG_DISPLAYINFRONT
// #define M_OEFLAG_BACKGROUND
// #define M_OEFLAG_BACKSAVE
// #define M_OEFLAG_RUNBEFOREFADEIN
 #define M_OEFLAG_MOVEMENTS
// #define M_OEFLAG_ANIMATIONS
 #define M_OEFLAG_TABSTOP
 #define M_OEFLAG_WINDOWPROC
 #define M_OEFLAG_VALUES
// #define M_OEFLAG_SPRITES
// #define M_OEFLAG_INTERNALBACKSAVE
// #define M_OEFLAG_SCROLLINGINDEPENDANT
// #define M_OEFLAG_QUICKDISPLAY
// #define M_OEFLAG_NEVERKILL
// #define M_OEFLAG_NEVERSLEEP
// #define M_OEFLAG_MANUALSLEEP
 #define M_OEFLAG_TEXT

// #define M_OEPREFS_BACKSAVE
// #define M_OEPREFS_SCROLLINGINDEPENDANT
// #define M_OEPREFS_QUICKDISPLAY
// #define M_OEPREFS_SLEEP
// #define M_OEPREFS_LOADONCALL
// #define M_OEPREFS_GLOBAL
// #define M_OEPREFS_BACKEFFECTS
// #define M_OEPREFS_KILL
// #define M_OEPREFS_INKEFFECTS
// #define M_OEPREFS_TRANSITIONS
// #define M_OEPREFS_FINECOLLISIONS