/* File generated by DarkEdifPostBuildTool v1.0.1.1, part of DarkEdif SDK.
   DarkEdif license is available at its online repository location.
   Copyright of the Phi Object extension and all rights reserved by the creator of Phi Object.

   A native iOS extension needs a Objective-C file to generate a Objective-C class.
   This file is required. The Phi Object creator may modify the copyright to suit their wishes,
   if they retain the DarkEdif notice (third line).
*/

//----------------------------------------------------------------------------------
// CRunPhi_Object
//----------------------------------------------------------------------------------
#import <Foundation/Foundation.h>
#import "CRunExtension.h"
#import "CExtStorage.h"

#if __cplusplus
extern "C" void Phi_Object_init();
extern "C" void Phi_Object_dealloc();
// Doesn't take a cptr, but you can't use it without SDK initialization - Phi_Object_init()
extern "C" int Phi_Object_getNumberOfConditions();
extern "C" long Phi_Object_conditionJump(void * cppExtPtr, int ID, void * paramReader);
extern "C" void Phi_Object_actionJump(void * cppExtPtr, int ID, void * paramReader);
extern "C" void Phi_Object_expressionJump(void * cppExtPtr, int ID);
extern "C" void * Phi_Object_createRunObject(void * file, void * cob, int version, void * objCExtPtr);
extern "C" short Phi_Object_handleRunObject(void * cppExtPtr);
extern "C" void Phi_Object_destroyRunObject(void * cppExtPtr, bool bFast);
#endif

static int initedPhi_ObjectCPP = 0;

@interface CRunPhi_Object : CRunExtension
{
@private
	void * cptr; // For 32-bit and 64-bit
@public
	CValue * expRet;
	BOOL proximityState;
	BOOL proximityWasEnabled;
}
-(int)getNumberOfConditions;
-(int)handleRunObject;
-(BOOL)createRunObject:(CFile*)file withCOB:(CCreateObjectInfo*)cob andVersion:(int)version;
-(void)destroyRunObject:(BOOL)bFast;
-(BOOL)condition:(int)num withCndExtension:(CCndExtension*)cnd;
-(void)action:(int)num withActExtension:(CActExtension*)act;
-(CValue*)expression:(int)num;

@end
